services:
  - type: web
    name: ud-giuliovn-predict-income
    env: docker
    repo: https://github.com/giuliovn/module3-deploying-a-scalable-ml-pipeline-in-production
    region: oregon
    plan: free
    branch: main
    rootDir: .
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: false  # will be deployed from CI/CD
